name: manal 

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and Push with gcloud builds submit
        env:
          REGION: us-central1
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPOSITORY: notely-ar-repo
          IMAGE: notely
          TAG: latest
        run: |
          # Use gcloud builds submit as required by the assignment
          gcloud builds submit \
            --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$TAG \
            .
